In [3]:
# Dependencies
import pandas as pd
from pathlib import Path

In [4]:
Mental_Disorders = Path("Resources/Mental health Depression disorder Data.csv")
Mental_Disorders_OGdf = pd.read_csv(Mental_Disorders, delimiter=',')

GDP_HealthExp = Path("Resources/World_Bank/HealthExpGDP%.csv")
GDP_HealthExp_OGdf = pd.read_csv(GDP_HealthExp, delimiter=',')

GDP = Path("Resources/World_Bank/GDP_USD.csv")
GDP_OGdf = pd.read_csv(GDP, delimiter = ',')

#Mental_Health = Path("Resources/Mental Health Dataset.csv")
#Mental_Health_df = pd.read_csv(Mental_Health)

#World_Bank = Path("Resources/2.12_Health_systems.csv")
#World_Bank_df = pd.read_csv(World_Bank)

/var/folders/m6/bhhzzj012vq18r_pf4rv2l640000gn/T/ipykernel_1782/1277549270.py:2: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  Mental_Disorders_OGdf = pd.read_csv(Mental_Disorders, delimiter=',')

In [5]:
Mental_Disorders_df_torename = Mental_Disorders_OGdf.drop('index', axis=1)

Mental_Disorders_df_torowdrop = Mental_Disorders_df_torename.rename(columns={"Entity": "Country Name", "Code": "Country Code"})

Mental_Disorders_df_todropna = Mental_Disorders_df_torowdrop.iloc[0:6468]

Mental_Disorders_df = Mental_Disorders_df_todropna.dropna()

Mental_Disorders_df

,Country Name,Country Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260
...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,0.15567,0.607993,0.117248,3.090168,0.766280,3.128192,1.515641
6464,Zimbabwe,ZWE,2014,0.155993,0.60861,0.118073,3.093964,0.768914,3.140290,1.515470
6465,Zimbabwe,ZWE,2015,0.156465,0.609363,0.11947,3.098687,0.771802,3.155710,1.514751
6466,Zimbabwe,ZWE,2016,0.157111,0.610234,0.121456,3.104294,0.772275,3.174134,1.513269
6467,Zimbabwe,ZWE,2017,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [6]:
GDP_HealthExp_df_tomelt = GDP_HealthExp_OGdf[["Country Name", "Country Code", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017"]]

GDP_HealthExp_df_todropna = GDP_HealthExp_df_tomelt.melt(id_vars=["Country Name", "Country Code"], var_name = "Year", value_name = "Percentage GDP Health Expenditure")

GDP_HealthExp_df = GDP_HealthExp_df_todropna.dropna()

GDP_HealthExp_df

,Country Name,Country Code,Year,Percentage GDP Health Expenditure
1,Africa Eastern and Southern,AFE,2010,6.445274
2,Afghanistan,AFG,2010,8.569672
3,Africa Western and Central,AFW,2010,3.498502
4,Angola,AGO,2010,2.695100
5,Albania,ALB,2010,6.236677
...,...,...,...,...
2121,World,WLD,2017,9.756479
2122,Samoa,WSM,2017,5.161202
2125,South Africa,ZAF,2017,7.977112
2126,Zambia,ZMB,2017,4.781562
2127,Zimbabwe,ZWE,2017,6.363583

In [10]:
GDP_df_tomelt = GDP_OGdf[["Country Name", "Country Code", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017"]]

GDP_df_todropna = GDP_df_tomelt.melt(id_vars=["Country Name", "Country Code"], var_name = "Year", value_name = "GDP (Current USD)")

GDP_df_toformat = GDP_df_todropna.dropna()

GDP_df_toformat["GDP (Current USD)"] = GDP_df_toformat["GDP (Current USD)"].map("${:,.2f}".format)
#GDP_df_toformat.loc[:, "GDP (Current USD)"] = GDP_df_toformat["GDP (Current USD)"].map("{:.2f}".format)

GDP_df = GDP_df_toformat

GDP_df

/var/folders/m6/bhhzzj012vq18r_pf4rv2l640000gn/T/ipykernel_1782/3584332359.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GDP_df_toformat["GDP (Current USD)"] = GDP_df_toformat["GDP (Current USD)"].map("${:,.2f}".format)

                     Country Name Country Code  Year    GDP (Current USD)
0                           Aruba          ABW  2010    $2,453,597,206.70
1     Africa Eastern and Southern          AFE  2010  $849,409,658,737.66
2                     Afghanistan          AFG  2010   $15,856,668,555.83
3      Africa Western and Central          AFW  2010  $598,697,706,331.00
4                          Angola          AGO  2010   $83,799,474,069.73
...                           ...          ...   ...                  ...
2123                       Kosovo          XKX  2017    $7,180,764,703.36
2124                  Yemen, Rep.          YEM  2017   $26,842,229,044.58
2125                 South Africa          ZAF  2017  $381,448,814,653.46
2126                       Zambia          ZMB  2017   $25,873,601,260.84
2127                     Zimbabwe          ZWE  2017   $17,584,890,936.65

[2071 rows x 4 columns]

In [8]:
HealthExp_Disorders_df = pd.merge(GDP_HealthExp_df, Mental_Disorders_df, on = ['Country Name', 'Country Code', 'Year'], how = 'inner')

GDP_HealthExp_Disorders_df = pd.merge(GDP_df, HealthExp_Disorders_df, on = ['Country Name', 'Country Code', 'Year'], how = 'inner')

GDP_HealthExp_Disorders_df

,Country Name,Country Code,Year,GDP (Current USD),Percentage GDP Health Expenditure,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,Afghanistan,AFG,2010,"$15,856,668,555.83",8.569672,0.16513,0.705313,0.097327,4.862777,2.571349,4.130874,0.662062
1,Angola,AGO,2010,"$83,799,474,069.73",2.695100,0.170158,0.622503,0.156364,3.277828,0.503415,4.155198,1.388193
2,Albania,ALB,2010,"$11,926,926,615.80",6.236677,0.199308,0.703064,0.160337,3.391246,0.500270,2.203342,1.838566
3,Andorra,AND,2010,"$3,449,925,738.86",7.675377,0.264305,0.961726,0.64824,5.287139,0.901630,3.708797,1.250824
4,United Arab Emirates,ARE,2010,"$300,189,052,688.90",3.878731,0.213138,0.80147,0.260129,4.200126,3.059998,2.860907,0.768782
...,...,...,...,...,...,...,...,...,...,...,...,...
1246,Vanuatu,VUT,2017,"$880,061,833.69",2.762855,0.214734,0.427419,0.106462,3.218816,0.698906,3.122695,1.213941
1247,Samoa,WSM,2017,"$884,844,384.46",5.161202,0.234876,0.460366,0.126132,3.255973,0.844905,3.038938,1.109339
1248,South Africa,ZAF,2017,"$381,448,814,653.46",7.977112,0.181937,0.636613,0.214718,3.992830,0.921499,3.745871,1.550514
1249,Zambia,ZMB,2017,"$25,873,601,260.84",4.781562,0.165866,0.605972,0.142768,3.599714,0.515972,3.641811,1.633243
1250,Zimbabwe,ZWE,2017,"$17,584,890,936.65",6.363583,0.157963,0.611242,0.124443,3.110926,0.772648,3.192789,1.510943

In [9]:
GDP_HealthExp_Disorders_df[GDP_HealthExp_Disorders_df['Country Name'] == 'Greece']

,Country Name,Country Code,Year,GDP (Current USD),Percentage GDP Health Expenditure,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
59,Greece,GRC,2010,"$297,124,961,971.50",9.596623,0.254124,0.946952,0.576268,5.803853,0.524963,4.324320,1.136287
216,Greece,GRC,2011,"$282,995,942,006.56",9.193303,0.25403,0.947111,0.576234,5.804698,0.528951,4.308968,1.136072
373,Greece,GRC,2012,"$242,029,307,133.41",8.924155,0.253911,0.947375,0.57508,5.804831,0.533145,4.291949,1.135864
529,Greece,GRC,2013,"$238,907,690,051.13",8.437964,0.25375,0.947666,0.573752,5.803820,0.537230,4.272856,1.135179
685,Greece,GRC,2014,"$235,458,133,124.61",7.891412,0.253543,0.947957,0.572011,5.801559,0.541156,4.252704,1.133881
841,Greece,GRC,2015,"$195,683,527,003.38",8.220045,0.2533,0.948286,0.568756,5.798518,0.545630,4.231759,1.131753
997,Greece,GRC,2016,"$193,148,146,586.93",8.448747,0.253015,0.948612,0.565342,5.794717,0.549305,4.208264,1.128556
1153,Greece,GRC,2017,"$199,844,406,013.53",8.135159,0.252701,0.948926,0.559324,5.790228,0.552602,4.185864,1.124257